export const HOME_IMAGE_SLIDER_REQUEST = "HOME_IMAGE_SLIDER_REQUEST";
export const HOME_IMAGE_SLIDER_SUCCESS = "HOME_IMAGE_SLIDER_SUCCESS";
export const HOME_IMAGE_SLIDER_ERROR = "HOME_IMAGE_SLIDER_ERROR";


export const CUSTOMER_REVIEW_LIST_REQUEST = "CUSTOMER_REVIEW_LIST_REQUEST";
export const CUSTOMER_REVIEW_LIST_SUCCESS = "CUSTOMER_REVIEW_LIST_SUCCESS";
export const CUSTOMER_REVIEW_LIST_ERROR = "CUSTOMER_REVIEW_LIST_ERROR";

export const CAR_WASH_REQUEST = "CAR_WASH_REQUEST";
export const CAR_WASH_SUCCESS = "CAR_WASH_SUCCESS";
export const CAR_WASH_ERROR = "CAR_WASH_ERROR";
